Tracker:AddLocations("locations/story.json")
Tracker:AddLocations("locations/nether.json")
Tracker:AddLocations("locations/end.json")
Tracker:AddLocations("locations/adventure.json")
Tracker:AddLocations("locations/ap.json")